version: '3.13'
services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:532"
  bot:
    build: ""
    command: sh -c "python -m BronBot"
    env_file:
      - .env
    restart: always
volumes:
  pgdata:
